<?php


define('DATALANDSCAPE_ADDRESS_FIELD', 'field_address');
define('DATALANDSCAPE_ADDRESS_TYPE', 'organisation');


function datalandscape_address_menu() {
    
    $items['address_parser'] = array(
        'title' => 'Event parser',
        'page callback' => '_datalandscape_address_parser',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
      );
    
    return $items;
}

function _datalandscape_address_parser(){
    
    global $user;
    // if ($user->uid != 1) die('This page is not available');
    
    if(isset($_GET['nid'])) {
        
        $nids = explode(",", $_GET['nid']);
    }
    else{
        $nids = db_select('node', 'n')
            ->fields('n', array('nid'))
            ->condition('n.type', DATALANDSCAPE_ADDRESS_TYPE)
            ->range(0,1000)
            ->execute()
            ->fetchCol();
    }
    
    foreach($nids as $nid) {
        
        $node = node_load($nid);
        $main_location = $node->field_main_location[LANGUAGE_NONE][0]['value'];
        
        $djson = Datalandscape_Geocoder::google_get($main_location, 'en', DATALANDSCAPE_GOOGLE_API_KEY);
        $data = Datalandscape_Geocoder::parse_json_response($djson);
        
       
        if($data != false) {

            $node->field_address[LANGUAGE_NONE][0]['country'] = $data->country_code;
            if(isset($data->locality) && !empty($data->locality)) {
                $node->field_address[LANGUAGE_NONE][0]['locality'] = $data->locality;
            }
            else if( isset($data->postal_town) && !empty($data->postal_town)){
                $node->field_address[LANGUAGE_NONE][0]['locality'] = $data->postal_town;
            }
            
            $node->field_address[LANGUAGE_NONE][0]['thoroughfare'] = trim($data->route . " " . $data->number);
            $node->field_address[LANGUAGE_NONE][0]['postal_code'] = $data->postal_code;

            node_save($node);
        }
        
        dsm($djson);
        dsm($node);
        dsm($data);
        
        
    }
    
    return '';
}


/*

function datalandscape_misc_menu() {
    
    $items['event_parser'] = array(
        'title' => 'Event parser',
        'page callback' => '_datalandscape_misc_parseevent',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
      );
    
    return $items;
}



function _get_tax_info($taxs, $tid){
    foreach($taxs as $tax){
        if($tax->tid == $tid){
            return $tax;
        }
    }
}

function _data_landscape_misc_get_taxonomies(){
    $taxs = taxonomy_get_tree(DATALANDSCAPE_VOCABULARY);
    return $taxs;
}

*/