<?php

function geocoder_rules_geocode($handler, $address) {
  $geometry = geocoder($handler, $address);

  watchdog("DEBUG GEOCODER RULES", var_export($geometry, true));
  $result = array(
    'longitude' => $geometry->coords[0],
    'latitude' => $geometry->coords[1],
    'accuracy' => $geometry->data['geocoder_accuracy'],
  );
  return $result;
}

function geocoder_rules_reverse_geocode($handler, $lat, $long, $language) {
  watchdog("DEBUG GEOCODER RULES", "long=$long, lat=$lat");
  $options = array();
  $options['language'] = $language;
  $address = geocoder_reverse($handler, $lat, $long, $options);

  watchdog("DEBUG GEOCODER RULES", var_export($address, true));
  
  return $address;
}

function geocoder_reverse($handler, $lat, $lng, $options=null) {

  $KEY_NOMINATIM = 'AqE69g28PEaock1GODOgm2rrEtuH4L3i';

  $url = "http://open.mapquestapi.com/nominatim/v1/reverse.php?format=json&lat=".$lat."&lon=".$lng."&accept-language=en&key=" . $KEY_NOMINATIM;

  $myadress = file_get_contents($url);

  $json = json_decode($myadress);

  if(isset($json->address)) {
    return (array) $json->address;
  }
  else{
    return array();
  }

}

