(function ($) {
    
    $(document).ready( function (){

        Highcharts.setOptions({
            lang : {
                numericSymbols: [ "k" , "M" , "B" , "T" , "P" , "E"]
            }
        });

        DataObject = function (title, datatable, suffix, information) { 
            this.n = 8; // tot - numbers of forecast scenarios
            this.title = title;
            this.datatable = datatable;
            this.ch_forecast = function() {
                return this.datatable['2025 Challenge'];
            };
            this.hg_forecast = function() {
                return this.datatable['2025 High Growth'];
            };
            this.data = function() {
                var a = Object.values(this.datatable);
                var d = a.slice(0, this.n);
                d.push(a[this.n+1]);
                return d;
            };
            if(suffix !== "undefined") {
                this.suffix = suffix;
            }
            if(information !== "undefined") {
                this.information = information;
            }
        };

        // Initialize the map.
        load_csv_eu('Data Market Value by MS','ms_dm_euro.csv', {'year':'2019', 'suffix': '€'});

        // Initialize Tooltips.
        // $('[data-toggle="tooltip"]').tooltip();

        // Configure objects. OK
        ndata_prof = new DataObject(
                'Number of Data Professionals by Member State',
                {
                    '2013': 5771861,
                    '2014': 5818004,
                    '2015': 6005430,
                    '2016': 6187465,
                    '2017': 6666109,
                    '2018': 7214503,
                    '2019': 7608299,
                    '2020': 8260894,
                    '2025 Challenge' : 10346145,
                    '2025 Baseline' : 11330565,
                    '2025 High Growth' : 13161809
                },
                '',
                'Data professionals are data workers who collect, store, manage, '
                + 'and/or analyse, interpret, and visualise data as their primary' 
                + ' or as a relevant part of their activity.'
            );


        // Ok.
        ndata_supp = new DataObject(
                'Number of Data Suppliers by Member State',
                {
                    '2013': 239845,
                    '2014': 243600,
                    '2015': 249100,
                    '2016': 261450,
                    '2017': 271700,
                    '2018': 283390,
                    '2019': 290000,
                    '2020': 297350,
                    '2025 Challenge' : 317230,
                    '2025 Baseline' : 334360,
                    '2025 High Growth' : 384020
                },
                '',
                'Data suppliers have as their main activity the production and delivery of digital data-related products, services, and technologies. They represent the supply side of the Data Market.'
                );

        // Ok.
        ndata_users = new DataObject(
                'Number of Data Users by Member State', 
                {
                    '2013': 633605,
                    '2014': 642700,
                    '2015': 650750,
                    '2016': 676150,
                    '2017': 691500,
                    '2018': 711870,
                    '2019': 715890,
                    '2020': 726110,
                    '2025 Challenge' : 753380,
                    '2025 Baseline' : 779150,
                    '2025 High Growth' : 845330
                }, '',
                'Data users are organisations that generate, exploit, collect and analyse digital data intensively and use what they learn to improve their business. They represent the demand side of the Data Market.'
                );

        // Ok.
        ndata_comprev = new DataObject(
                'Data Companies Revenues',
                {
                    '2013' : 47800798672,
                    '2014' : 51685716121,
                    '2015' : 56032512124,
                    '2016' : 61780930523,
                    '2017': 68845781720,
                    '2018': 77297414935,
                    '2019': 83545021119,
                    '2020': 91317998604,
                    '2025 Challenge': 103796426907,
                    '2025 Baseline': 127975619371,
                    '2025 High Growth': 181794911096,
                }, ' €',
                'Data companies’ revenues are the revenues generated by data suppliers for the products and services specified in our definition of the Data Market. The revenues correspond to the aggregated value of all the data-related products and services generated by Europe-based suppliers, including exports outside the EU.'
                        );

        // Ok. 
        ndata_market = new DataObject(
                'Data Market Value',
                {
                    '2013' : 47420000000,
                    '2014' : 50887847698,
                    '2015' : 54350740133,
                    '2016' : 59496022567,
                    '2017' : 65286367633,
                    '2018' : 71786716176,
                    '2019' : 75274247040,
                    '2020' : 80253427632,
                    '2025 Challenge' : 93055541842,
                    '2025 Baseline' : 105638123008,
                    '2025 High Growth' : 141507195947
                }, ' €',
                'The Data Market is the marketplace where digital data is exchanged as “products” or “services” as a result of the elaboration of raw data. We define its value as the aggregate value of the demand of digital data without measuring the direct, indirect and induced impacts of data in the economy.'
                );        

        // Ok. 
        ndata_ecoval = new DataObject(
                'Data Economy Value', 
                {
                    '2013' : 246840437767,
                    '2014' : 257588952289,
                    '2015' : 285633450361,
                    '2016' : 299989232864,
                    '2017' : 336601997533,
                    '2018' : 377870881962,
                    '2019' : 406468227949,
                    '2020' : 443924992043,
                    '2025 Challenge' : 536715045904,
                    '2025 Baseline' : 674263136080,
                    '2025 High Growth' : 1036709357060
                }, ' €', 
                'The Data Economy measures the overall impacts of the Data Market on the economy. It involves the generation, collection, storage, processing, distribution, analysis elaboration, delivery, and exploitation of data enabled by digital technologies. The Data Economy also includes the direct, indirect, and induced effects of the Data Market on the economy.'
                );


        // Ok.
        ndata_empshare = new DataObject(
                'Employment Share of Data Professionals', 
                {
                    '2013' : 3,
                    '2014' : 3,
                    '2015' : 3.1,
                    '2016' : 3.1,
                    '2017' : 3.3,
                    '2018' : 3.5,
                    '2019' : 3.6,
                    '2020' : 3.8,
                    '2025 Challenge' : null,
                    '2025 Baseline' : null,
                    '2025 High Growth' : null
                }, ' %');

        // ok.
        ndata_ictspend = new DataObject(
                'Share of Data Market on ICT Spending', 
                {
                    '2013' : 8.1,
                    '2014' : 8.7,
                    '2015' : 8.8,
                    '2016' : 9.8,
                    '2017': 10.6,
                    '2018': 11.3,
                    '2019': 11.4,
                    '2020': 11.9,
                    '2025 Challenge': 12.8,
                    '2025 Baseline': 14.0,
                    '2025 High Growth': 18.2
                }, ' %');

        // Ok.
        ndata_dctotal = new DataObject(
                'Data Economy impacts on GDP', 
                {
                    '2013': 1.9,
                    '2014': 1.9,
                    '2015': 2.0,
                    '2016': 2.2,
                    '2017': 2.4,
                    '2018': 2.6,
                    '2019': 2.8,
                    '2020': 3.0,
                    '2025 Challenge': 3.4,
                    '2025 Baseline': 4.2,
                    '2025 High Growth': 6.2
                }, ' %',
                'Data Economy Value Total impacts as a percentage on GDP');

        // Ok.
        ndata_shareusercomp = new DataObject(
                'Share of data users of total EU Companies', 
                {
                    '2013' : null, 
                    '2014' : 6.3,
                    '2015' : 6.3,
                    '2016' : 6.5,
                    '2017': 6.6,
                    '2018': 6.7,
                    '2019': 6.7,
                    '2020': 6.8,
                    '2025 Challenge': 7.0,
                    '2025 Baseline': 7.2,
                    '2025 High Growth': 7.8
                }, ' %');

        // Ok.
        ndata_share_data_supp_jm = new DataObject(
                '',
                {
                    '2013' : null, 
                    '2014' : 13.6,
                    '2015' : 13.8,
                    '2016' : 14.2,
                    '2017': 14.8,
                    '2018': 15.2,
                    '2019': 15.2,
                    '2020': 15.4,
                    '2025 Challenge': 16.0,
                    '2025 Baseline': 16.7,
                    '2025 High Growth': 28.9
                }, ' %',
                'Share of data suppliers as a percentage on total companies in sectors J and M');        

        // Ok.
        ndata_share_data_company_jm = new DataObject(
                '',
                {
                    '2013' : 3,
                    '2014' : 3.2,
                    '2015' : 3.4,
                    '2016' : 3.1,
                    '2017' : 3.3,
                    '2018' : 3.5,
                    '2019' : 3.7,
                    '2020' : null,
                    '2025 Challenge' : null,
                    '2025 Baseline' : null,
                    '2025 High Growth' : null
                }, 
                ' %',
                'Share of data companies revenues as a percentage on total companies generated in sectors J and M'
            );        


        // Data Market
        gline_summary('tline-ndata-market', ndata_market);
        render_table_normal('ttab-ndata-market', ndata_market);

        // Data Economy Value
        gline_summary('tline-ndata-ecoval', ndata_ecoval);
        render_table_normal('ttab-ndata-ecoval', ndata_ecoval);

        // Data Professionals
        gline_summary('tline-ndata-prof', ndata_prof);
        render_table_normal('ttab-ndata-prof', ndata_prof);

        // Data Suppliers
        gline_summary('tline-ndata-supp', ndata_supp);
        render_table_normal('ttab-ndata-supp', ndata_supp);

        // Data Suppliers
        gline_summary('tline-ndata-users', ndata_users);
        render_table_normal('ttab-ndata-users', ndata_users);

        // Data Suppliers
        gline_summary('tline-ndata-comprev', ndata_comprev);
        render_table_normal('ttab-ndata-comprev', ndata_comprev);

        gline_summary('tline-ndata-empshare', ndata_empshare);
        render_table_normal('ttab-ndata-empshare', ndata_empshare);

        gline_summary('tline-ndata-ictspend', ndata_ictspend);
        render_table_normal('ttab-ndata-ictspend', ndata_ictspend);

        gline_summary('tline-ndata-dctotal', ndata_dctotal);
        render_table_normal('ttab-ndata-dctotal', ndata_dctotal);

        gline_summary('tline-ndata-shareusercomp', ndata_shareusercomp);
        render_table_normal('ttab-ndata-shareusercomp', ndata_shareusercomp);

        gline_summary('tline-ndata-sharedatasuppjs', ndata_share_data_supp_jm);
        render_table_normal('ttab-ndata-sharedatasuppjs', ndata_share_data_supp_jm);

        gline_summary('tline-ndata-sharedcjs', ndata_share_data_company_jm);
        render_table_normal('ttab-ndata-sharedcjs', ndata_share_data_company_jm);


        /* Call for industries */
        gline_summary('tline-indu-market', ndata_market);
        render_table_normal('ttab-indu-market', ndata_market);

        // Data Economy Value
        gline_summary('tline-indu-ecoval', ndata_ecoval);
        render_table_normal('ttab-indu-ecoval', ndata_ecoval);

        // Data Professionals
        gline_summary('tline-indu-prof', ndata_prof);
        render_table_normal('ttab-indu-prof', ndata_prof);

        // Data Suppliers
        gline_summary('tline-indu-supp', ndata_supp);
        render_table_normal('ttab-indu-supp', ndata_supp);

        // Data Suppliers
        gline_summary('tline-indu-users', ndata_users);
        render_table_normal('ttab-indu-users', ndata_users);

        // Data Suppliers
        gline_summary('tline-indu-comprev', ndata_comprev);
        render_table_normal('ttab-indu-comprev', ndata_comprev);

        gline_summary('tline-indu-empshare', ndata_empshare);
        render_table_normal('ttab-indu-empshare', ndata_empshare);

        gline_summary('tline-indu-ictspend', ndata_ictspend);
        render_table_normal('ttab-indu-ictspend', ndata_ictspend);

        gline_summary('tline-indu-dctotal', ndata_dctotal);
        render_table_normal('ttab-indu-dctotal', ndata_dctotal);

        gline_summary('tline-indu-shareusercomp', ndata_shareusercomp);
        render_table_normal('ttab-indu-shareusercomp', ndata_shareusercomp);

        gline_summary('tline-indu-sharedatasuppjs', ndata_share_data_supp_jm);
        render_table_normal('ttab-indu-sharedatasuppjs', ndata_share_data_supp_jm);

        gline_summary('tline-indu-sharedcjs', ndata_share_data_company_jm);
        render_table_normal('ttab-indu-sharedcjs', ndata_share_data_company_jm);


        // Hide the additional rows and the graphs.
        $('.ttab table tr.row-hide').hide();
        $('.tline').hide();

        // Trigger the "show more" row
        $(document).on('click', '.tr-toggle', function(ev, el){
            // toggle rows
            $(this).parent().find('tr.row-hide').toggle('fast');

            // toggle graph
            var id_graph=$(this).parents('.ttab').attr('id').replace('ttab','tline');

            var status = $('#' + id_graph).is(':visible');

            var txt = (status) ? 'Show more' : 'Show less';
            $(this).find('span').html(txt);

            $('#'+id_graph).slideToggle();
        });

        // Fill with the background color.
        $('.c2').each( function(i, el) {
            setFill(el, $(el).data('perc'), true);
        });

        // Activate the select field for the vars change in the map.
        $('#msvar').on('change', function (el) {
            var csvfile = $(this).val() + '.csv';
            var $optsel = $(this).find("option:selected");
            var varname = $.trim($optsel.text().replace(/ ?\(.{1}\) */, ''));
            var selected_year = $optsel.data('year');
            var suffix = $optsel.data('suffix');
            load_csv_eu(varname, csvfile, {'year':selected_year, 'suffix':suffix}, false);
        });

        $('#induvar').on('change', function () {
            // $('#indu-img').attr('src', 'assets/img/png/' + $(this).val() + '.png');
            var $optsel = $(this).find("option:selected");
            var suffix = $optsel.data('suffix');
            di = load_industries_csv('', $(this).val() + '.csv', suffix);
        });

        /* Gapminder - MS + Indu */
        var ddfcsvReader = new DDFCsvReader.getDDFCsvReaderObject();
        Vizabi.Reader.extend("ddf", ddfcsvReader);

        var viz = Vizabi('BubbleChart', document.getElementById('placeholder-gap-ms'), GAPMS_CONFIG);
        var viz2 = null;

        $('a[data-toggle="tab"]#trigger_indu').on('shown.bs.tab', function (e) {
            if(viz2 === null) {
                viz2 = Vizabi('BubbleChart', document.getElementById('placeholder-gap-indu'), GAPINDU_CONFIG);
            }

            di = load_industries_csv('', 'indu_dm_euro.csv', '€');
        })

    });

}(jQuery));